set(_CATKIN_CURRENT_PACKAGE "iiwa_visual_servoing")
set(iiwa_visual_servoing_VERSION "0.0.0")
set(iiwa_visual_servoing_MAINTAINER "charlie <charlie@todo.todo>")
set(iiwa_visual_servoing_PACKAGE_FORMAT "2")
set(iiwa_visual_servoing_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "iiwa_test")
set(iiwa_visual_servoing_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "stensor_msgs")
set(iiwa_visual_servoing_BUILDTOOL_DEPENDS "catkin")
set(iiwa_visual_servoing_BUILDTOOL_EXPORT_DEPENDS )
set(iiwa_visual_servoing_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "iiwa_test")
set(iiwa_visual_servoing_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "iiwa_test" "stensor_msgs")
set(iiwa_visual_servoing_TEST_DEPENDS )
set(iiwa_visual_servoing_DOC_DEPENDS )
set(iiwa_visual_servoing_URL_WEBSITE "")
set(iiwa_visual_servoing_URL_BUGTRACKER "")
set(iiwa_visual_servoing_URL_REPOSITORY "")
set(iiwa_visual_servoing_DEPRECATED "")