set(_CATKIN_CURRENT_PACKAGE "force_sensor")
set(force_sensor_VERSION "0.0.0")
set(force_sensor_MAINTAINER "charlie <charlie@todo.todo>")
set(force_sensor_PACKAGE_FORMAT "2")
set(force_sensor_BUILD_DEPENDS "roscpp" "std_msgs")
set(force_sensor_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(force_sensor_BUILDTOOL_DEPENDS "catkin")
set(force_sensor_BUILDTOOL_EXPORT_DEPENDS )
set(force_sensor_EXEC_DEPENDS "roscpp" "std_msgs")
set(force_sensor_RUN_DEPENDS "roscpp" "std_msgs")
set(force_sensor_TEST_DEPENDS )
set(force_sensor_DOC_DEPENDS )
set(force_sensor_URL_WEBSITE "")
set(force_sensor_URL_BUGTRACKER "")
set(force_sensor_URL_REPOSITORY "")
set(force_sensor_DEPRECATED "")