set(_CATKIN_CURRENT_PACKAGE "iiwa_test")
set(iiwa_test_VERSION "0.0.0")
set(iiwa_test_MAINTAINER "charlie <charlie@todo.todo>")
set(iiwa_test_PACKAGE_FORMAT "2")
set(iiwa_test_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "message_generation")
set(iiwa_test_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(iiwa_test_BUILDTOOL_DEPENDS "catkin")
set(iiwa_test_BUILDTOOL_EXPORT_DEPENDS )
set(iiwa_test_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "message_runtime")
set(iiwa_test_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "message_runtime")
set(iiwa_test_TEST_DEPENDS )
set(iiwa_test_DOC_DEPENDS )
set(iiwa_test_URL_WEBSITE "")
set(iiwa_test_URL_BUGTRACKER "")
set(iiwa_test_URL_REPOSITORY "")
set(iiwa_test_DEPRECATED "")